# Generated by Django 4.0.1 on 2022-01-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_empleados_email_empleados_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convocatoria', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='votaciones',
            name='convocatoria',
        ),
        migrations.AddField(
            model_name='votaciones',
            name='inicio',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='votaciones',
            name='publicacion',
            field=models.BooleanField(),
        ),
    ]
