# Generated by Django 4.0.1 on 2022-01-12 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_configuracion_remove_votaciones_convocatoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='username',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='verificado',
        ),
        migrations.AddField(
            model_name='empleados',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
