# Generated by Django 4.0.1 on 2022-01-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_empleados_groups_empleados_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votaciones',
            name='inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='votaciones',
            name='publicacion',
            field=models.DateTimeField(),
        ),
    ]
