# Generated by Django 4.0.1 on 2022-01-14 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_votaciones_inicio_alter_votaciones_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votos',
            name='id_votaciones',
        ),
        migrations.AddField(
            model_name='candidatos',
            name='id_votaciones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.votaciones'),
        ),
        migrations.AddField(
            model_name='votos_empleados',
            name='emision',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
