# Generated by Django 4.0.1 on 2022-01-17 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_votos_id_votaciones_candidatos_id_votaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='id_votaciones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidatura', to='api.votaciones'),
        ),
    ]
