# Generated by Django 4.0.1 on 2022-01-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_candidatos_id_votaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='is_authenticated',
        ),
    ]
