# Generated by Django 4.0.1 on 2022-01-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_empleados_is_anonymous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votos',
            name='id_votacion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.votaciones'),
        ),
    ]
