# Generated by Django 4.0.1 on 2022-03-17 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_votos_id_votacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='datos_empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('no_expediente', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='candidatos',
            name='id_votaciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.votaciones'),
        ),
    ]
